/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package padariafinal.GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import padariafinal.DB.ClienteDB;
import padariafinal.DB.ProdutoDB;
import padariafinal.DB.VendaDB;
import padariafinal.MODEL.Cliente;
import padariafinal.MODEL.Produto;
import padariafinal.MODEL.Venda;

/**
 *
 * @author pa-to
 */
public class CadastrarVendaJInternalFrame extends javax.swing.JInternalFrame {
    DefaultTableModel modelTableProduto = new DefaultTableModel(){
      @Override
      public boolean isCellEditable(int row, int column){
          float preco = (float) produtosTable.getValueAt(row, 3);
          String quantidadeStr = quantidadeCb.getItemAt(quantidadeCb.getSelectedIndex());
          float total = preco* Float.parseFloat(quantidadeStr);
          totalTxt.setText(String.valueOf(total));
          
          
          return false;
      } 
    };
    DefaultTableModel modelTableCliente = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
            return false;
      } 
    };
    
    /**
     * Creates new form CadastrarVendaJInternalFrame
     */
    public CadastrarVendaJInternalFrame() {
        initComponents();
        loadClientesTable();
        loadProdutosTable();
        loadQuantidadeCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clientesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        produtosTable = new javax.swing.JTable();
        quantidadeCb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JTextField();
        fecharBtn = new javax.swing.JButton();
        venderBtn = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Cadastrar Venda");

        clientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(clientesTable);

        jLabel1.setText("Clientes");

        jLabel2.setText("Produtos");

        produtosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(produtosTable);

        quantidadeCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeCbActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade");

        jLabel4.setText("Total R$");

        totalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTxtActionPerformed(evt);
            }
        });

        fecharBtn.setText("Fechar");
        fecharBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharBtnActionPerformed(evt);
            }
        });

        venderBtn.setText("Vender");
        venderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalTxt)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantidadeCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(326, 326, 326))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(729, 729, 729)
                                .addComponent(venderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(fecharBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(809, 809, 809))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(822, 822, 822)))
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidadeCb)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalTxt)
                        .addGap(119, 119, 119))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecharBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(venderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTxtActionPerformed

    private void fecharBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBtnActionPerformed
      this.dispose();
    }//GEN-LAST:event_fecharBtnActionPerformed

    private void venderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderBtnActionPerformed
       int linhaSelecionadaProdutos = produtosTable.getSelectedRow();
       int linhaSelecionadaClientes= clientesTable.getSelectedRow();
       
       if(linhaSelecionadaProdutos==-1 && linhaSelecionadaClientes==-1){
           JOptionPane.showMessageDialog(rootPane, "Selecione um cliente, um produto e uma quantidade!");
           return;
       }else if(linhaSelecionadaProdutos==-1){
           JOptionPane.showMessageDialog(rootPane, "Selecione um produto e a quantidade!");
           return;
       }else if (linhaSelecionadaClientes==-1){
           JOptionPane.showMessageDialog(rootPane, "Selecione um cliente!");
           return;
       }
       
       int idProduto = (int) produtosTable.getValueAt(linhaSelecionadaProdutos, 0);
       int idCliente = (int) clientesTable.getValueAt(linhaSelecionadaClientes, 0);
       String quantidadeStr=quantidadeCb.getItemAt(quantidadeCb.getSelectedIndex());
       int quantidade = Integer.parseInt(quantidadeStr);
       Venda venda = new Venda (idCliente, idProduto,quantidade);
       VendaDB vendaDB=new VendaDB();
        if(vendaDB.insert(venda)){
           JOptionPane.showMessageDialog(rootPane, "Vendido com sucesso!");
           totalTxt.setText("");
           produtosTable.clearSelection();
           clientesTable.clearSelection();
           quantidadeCb.setSelectedIndex(1);
           
       }
       else{
           JOptionPane.showMessageDialog(rootPane, "Erro venda nao efetuada!");
       }
    }//GEN-LAST:event_venderBtnActionPerformed

    private void quantidadeCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeCbActionPerformed
        int linhaSelecionada=produtosTable.getSelectedRow();
        if(linhaSelecionada!=-1){
            float preco = (float) produtosTable.getValueAt(linhaSelecionada, 3);
            String quantidadeStr = quantidadeCb.getItemAt(quantidadeCb.getSelectedIndex());
            float total = preco* Float.parseFloat(quantidadeStr);
            totalTxt.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_quantidadeCbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clientesTable;
    private javax.swing.JButton fecharBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable produtosTable;
    private javax.swing.JComboBox<String> quantidadeCb;
    private javax.swing.JTextField totalTxt;
    private javax.swing.JButton venderBtn;
    // End of variables declaration//GEN-END:variables

     private void loadClientesTable(){
         modelTableCliente.addColumn("idCliente");
         modelTableCliente.addColumn("Nome");
         modelTableCliente.addColumn("CPF");
         modelTableCliente.addColumn("Email");
         
         ClienteDB clienteDB = new ClienteDB();
         ArrayList<Cliente> clientes =  clienteDB.getClientes();
         
         for(int i =0; i<clientes.size();i++){
             Cliente cliente = (Cliente) clientes.get(i);
             int idCliente = cliente.getIdCliente();
             String nome = cliente.getNome();
             String CPF = cliente.getCPF();
             String email = cliente.getEmail();
             
             modelTableCliente.addRow(new Object[] 
             {idCliente,nome,CPF,email});
             
         }
         
         clientesTable.setModel(modelTableCliente);
         jScrollPane1.setViewportView(clientesTable);
    }
    
    private void loadProdutosTable() {
         modelTableProduto.addColumn("idProduto");
         modelTableProduto.addColumn("Nome");
         modelTableProduto.addColumn("Descricao");
         modelTableProduto.addColumn("Preco");
         
         ProdutoDB produtoDB = new ProdutoDB();
         ArrayList<Produto> produtos =  produtoDB.getProdutos();
         
         for(int i =0; i<produtos.size();i++){
             Produto produto = (Produto) produtos.get(i);
             int idProduto = produto.getIdProduto();
             String nome = produto.getNome();
             String descricao = produto.getDescricao();
             float preco = produto.getPreco();
             
             modelTableProduto.addRow(new Object[] 
             {idProduto,nome,descricao,preco});
             
         }
         
         produtosTable.setModel(modelTableProduto);
         jScrollPane2.setViewportView(produtosTable);
    }

    private void loadQuantidadeCombo() {
        for(int i=1;i<=20;i++){
            quantidadeCb.addItem(String.valueOf(i));
        }
    }
    
    
}
