/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package padariafinal.GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import padariafinal.DB.ClienteDB;
import padariafinal.DB.ProdutoDB;
import padariafinal.MODEL.Cliente;
import padariafinal.MODEL.Produto;

/**
 *
 * @author pa-to
 */
public class EditarProdutoJInternalFrame extends javax.swing.JInternalFrame {

     DefaultTableModel modelProdutoTable = new DefaultTableModel(){
        public boolean isCellEditable(int row, int column){
            if (column==0){
                JOptionPane.showMessageDialog(null, "Esse valor nao é editavel!");
                return false;
                
            }
            return true;
        }
    };
    /**
     * Creates new form EditarProdutoJInternalFrame
     */
    public EditarProdutoJInternalFrame() {
        initComponents();
        loadProdutosTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        produtosTable = new javax.swing.JTable();
        fecharBtn = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Editar Produto");

        produtosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(produtosTable);

        fecharBtn.setText("Fechar");
        fecharBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharBtnActionPerformed(evt);
            }
        });

        editarBtn.setText("Editar");
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fecharBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecharBtn)
                    .addComponent(editarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharBtnActionPerformed

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
         int linhaSelecionadaProdutos = produtosTable.getSelectedRow();
      
      if(linhaSelecionadaProdutos==-1){
           JOptionPane.showMessageDialog(rootPane, "Selecione um Cliente da tabela!");
        return;  
      }
          
      
      int idProduto = (int) produtosTable.getValueAt(linhaSelecionadaProdutos, 0);
      String nome = (String) produtosTable.getValueAt(linhaSelecionadaProdutos, 1);
      String descricao = (String) produtosTable.getValueAt(linhaSelecionadaProdutos, 2);
      String precoStr = (String) produtosTable.getValueAt(linhaSelecionadaProdutos,3);
      float preco = Float.parseFloat(precoStr);
      
      
      
      Produto produto = new Produto(idProduto,nome,descricao, preco );
      ProdutoDB produtoDB = new ProdutoDB();
      if(produtoDB.update(produto)){
          JOptionPane.showMessageDialog(rootPane, "Produto atualizado com sucesso!");
          produtosTable.clearSelection();
      }else{
          JOptionPane.showMessageDialog(rootPane, "Houve um problema em atualizar os dados!");
      }
      
      
    }//GEN-LAST:event_editarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarBtn;
    private javax.swing.JButton fecharBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable produtosTable;
    // End of variables declaration//GEN-END:variables

    private void loadProdutosTable() {
       
        modelProdutoTable.addColumn("IdProduto");
        modelProdutoTable.addColumn("Nome");
        modelProdutoTable.addColumn("Descricao");
        modelProdutoTable.addColumn("Preco");
        
        ProdutoDB produtoDB=new ProdutoDB();
        ArrayList<Produto> produtos = produtoDB.getProdutos();
        
        for(int i=0;i<produtos.size();i++){
            Produto produto = (Produto) produtos.get(i);
            int idProduto = produto.getIdProduto();
            String nome = produto.getNome();
            String descricao=produto.getDescricao();
            float preco=produto.getPreco();
            
            modelProdutoTable.addRow(new Object[]{idProduto,nome,descricao,preco });
        }
        produtosTable.setModel(modelProdutoTable);
        jScrollPane1.setViewportView(produtosTable);
    }
    
}
