/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package padariafinal.GUI;

/**
 *
 * @author pa-to
 */
public class MDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form MDIApplication
     */
    public MDIApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        cadastrarMenu = new javax.swing.JMenu();
        cadastrarClienteMenuItem = new javax.swing.JMenuItem();
        CadastrarProdutoMenuItem = new javax.swing.JMenuItem();
        CadastrarVendaItemMenu = new javax.swing.JMenuItem();
        editarMenu = new javax.swing.JMenu();
        editarClienteMenuItem = new javax.swing.JMenuItem();
        editarProdutoMenuItem = new javax.swing.JMenuItem();
        editarVendaMenuItem = new javax.swing.JMenuItem();
        removerMenu = new javax.swing.JMenu();
        removerClienteMenuItem = new javax.swing.JMenuItem();
        removerProdutoMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema da Padaria Pao De Mel");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/padariafinal/GUI/padaria-doces-paes-logo-7CD74307A4-seeklogo.com.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(490, 180, 290, 310);

        cadastrarMenu.setMnemonic('f');
        cadastrarMenu.setText("Cadastrar");

        cadastrarClienteMenuItem.setMnemonic('o');
        cadastrarClienteMenuItem.setText("Cliente");
        cadastrarClienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteMenuItemActionPerformed(evt);
            }
        });
        cadastrarMenu.add(cadastrarClienteMenuItem);

        CadastrarProdutoMenuItem.setMnemonic('s');
        CadastrarProdutoMenuItem.setText("Produto");
        CadastrarProdutoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProdutoMenuItemActionPerformed(evt);
            }
        });
        cadastrarMenu.add(CadastrarProdutoMenuItem);

        CadastrarVendaItemMenu.setText("Venda");
        CadastrarVendaItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarVendaItemMenuActionPerformed(evt);
            }
        });
        cadastrarMenu.add(CadastrarVendaItemMenu);

        menuBar.add(cadastrarMenu);

        editarMenu.setText("Editar");

        editarClienteMenuItem.setMnemonic('t');
        editarClienteMenuItem.setText("Cliente");
        editarClienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarClienteMenuItemActionPerformed(evt);
            }
        });
        editarMenu.add(editarClienteMenuItem);

        editarProdutoMenuItem.setMnemonic('y');
        editarProdutoMenuItem.setText("Produto");
        editarProdutoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProdutoMenuItemActionPerformed(evt);
            }
        });
        editarMenu.add(editarProdutoMenuItem);

        editarVendaMenuItem.setMnemonic('p');
        editarVendaMenuItem.setText("Venda");
        editarVendaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarVendaMenuItemActionPerformed(evt);
            }
        });
        editarMenu.add(editarVendaMenuItem);

        menuBar.add(editarMenu);

        removerMenu.setMnemonic('h');
        removerMenu.setText("Remover");

        removerClienteMenuItem.setText("Cliente");
        removerClienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerClienteMenuItemActionPerformed(evt);
            }
        });
        removerMenu.add(removerClienteMenuItem);

        removerProdutoMenuItem.setMnemonic('a');
        removerProdutoMenuItem.setText("Produto");
        removerProdutoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerProdutoMenuItemActionPerformed(evt);
            }
        });
        removerMenu.add(removerProdutoMenuItem);

        jMenuItem1.setText("Venda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        removerMenu.add(jMenuItem1);

        menuBar.add(removerMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarVendaItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarVendaItemMenuActionPerformed
        CadastrarVendaJInternalFrame cadIF = new CadastrarVendaJInternalFrame();
        desktopPane.add(cadIF);
        cadIF.setVisible(true);
                      
    }//GEN-LAST:event_CadastrarVendaItemMenuActionPerformed

    private void editarClienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarClienteMenuItemActionPerformed
        EditarClienteJInternalFrame editIF = new EditarClienteJInternalFrame();
        desktopPane.add(editIF);
        editIF.setVisible(true);
    }//GEN-LAST:event_editarClienteMenuItemActionPerformed

    private void CadastrarProdutoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProdutoMenuItemActionPerformed
       CadastrarProdutoJInternalFrame cadIF = new CadastrarProdutoJInternalFrame();
       desktopPane.add(cadIF);
       cadIF.setVisible(true);
    }//GEN-LAST:event_CadastrarProdutoMenuItemActionPerformed

    private void editarVendaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarVendaMenuItemActionPerformed
        EditarVendaJInternalFrame editIF = new EditarVendaJInternalFrame();
        desktopPane.add(editIF);
        editIF.setVisible(true);
    }//GEN-LAST:event_editarVendaMenuItemActionPerformed

    private void removerProdutoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerProdutoMenuItemActionPerformed
        RemoverProdutoJInternalFrame remIF = new RemoverProdutoJInternalFrame();
        desktopPane.add(remIF);
        remIF.setVisible(true);
    }//GEN-LAST:event_removerProdutoMenuItemActionPerformed

    private void cadastrarClienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteMenuItemActionPerformed
        CadastrarClienteJInternalFrame cadIF = new CadastrarClienteJInternalFrame();
        desktopPane.add(cadIF);
        cadIF.setVisible(true);
    }//GEN-LAST:event_cadastrarClienteMenuItemActionPerformed

    private void editarProdutoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProdutoMenuItemActionPerformed
        EditarProdutoJInternalFrame editIF = new EditarProdutoJInternalFrame();
        desktopPane.add(editIF);
        editIF.setVisible(true);
    }//GEN-LAST:event_editarProdutoMenuItemActionPerformed

    private void removerClienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerClienteMenuItemActionPerformed
        RemoverClienteJInternalFrame remIF = new RemoverClienteJInternalFrame();
        desktopPane.add(remIF);
        remIF.setVisible(true);
    }//GEN-LAST:event_removerClienteMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        RemoverVendaJInternalFrame remIF = new RemoverVendaJInternalFrame();
        desktopPane.add(remIF);
        remIF.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastrarProdutoMenuItem;
    private javax.swing.JMenuItem CadastrarVendaItemMenu;
    private javax.swing.JMenuItem cadastrarClienteMenuItem;
    private javax.swing.JMenu cadastrarMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem editarClienteMenuItem;
    private javax.swing.JMenu editarMenu;
    private javax.swing.JMenuItem editarProdutoMenuItem;
    private javax.swing.JMenuItem editarVendaMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem removerClienteMenuItem;
    private javax.swing.JMenu removerMenu;
    private javax.swing.JMenuItem removerProdutoMenuItem;
    // End of variables declaration//GEN-END:variables

}
