/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package padariafinal.GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import padariafinal.DB.ClienteDB;
import padariafinal.DB.ProdutoDB;
import padariafinal.MODEL.Produto;

public class RemoverProdutoJInternalFrame extends javax.swing.JInternalFrame {

    DefaultTableModel modelProdutoTable = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {

            return false;
        }
    };

    public RemoverProdutoJInternalFrame() {
        initComponents();
        loadProdutosTable();
    }

    private void loadProdutosTable() {

        modelProdutoTable.addColumn("IdProduto");
        modelProdutoTable.addColumn("Nome");
        modelProdutoTable.addColumn("Descricao");
        modelProdutoTable.addColumn("Preco");

        ProdutoDB produtoDB = new ProdutoDB();
        ArrayList<Produto> produtos = produtoDB.getProdutos();

        for (int i = 0; i < produtos.size(); i++) {
            Produto produto = (Produto) produtos.get(i);
            int idProduto = produto.getIdProduto();
            String nome = produto.getNome();
            String descricao = produto.getDescricao();
            float preco = produto.getPreco();

            modelProdutoTable.addRow(new Object[]{idProduto, nome, descricao, preco});
        }
        produtosTable.setModel(modelProdutoTable);
        jScrollPane1.setViewportView(produtosTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        produtosTable = new javax.swing.JTable();
        fecharBtn = new javax.swing.JButton();
        removerBtn = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Remover Produto");

        produtosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(produtosTable);

        fecharBtn.setText("Fechar");
        fecharBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharBtnActionPerformed(evt);
            }
        });

        removerBtn.setText("Remover");
        removerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(removerBtn)
                        .addGap(18, 18, 18)
                        .addComponent(fecharBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecharBtn)
                    .addComponent(removerBtn))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBtnActionPerformed
        int linhaSelecionadaProdutos = produtosTable.getSelectedRow();

        if (linhaSelecionadaProdutos == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Produto da tabela!");
            return;
        }

        int idProduto = (int) produtosTable.getValueAt(linhaSelecionadaProdutos, 0);

        ProdutoDB produtoDB = new ProdutoDB();
        if (produtoDB.hasVenda(idProduto)) {
            int res = JOptionPane.showConfirmDialog(rootPane, "Este produto possui uma ou mais vendas, exclua suas vendas para poder excluir o Produto");
            if (res == JOptionPane.YES_OPTION) {
                if (produtoDB.delete(idProduto)) {
                    JOptionPane.showMessageDialog(rootPane, "Produto Removido com sucesso!");
                    modelProdutoTable.removeRow(linhaSelecionadaProdutos);
                    produtosTable.setModel(modelProdutoTable);
                    jScrollPane1.setViewportView(produtosTable);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Houve um problema em Remover os dados!");
                }

            }
        } else {
            if (produtoDB.delete(idProduto)) {
                JOptionPane.showMessageDialog(rootPane, "Produto Removido com sucesso!");
                modelProdutoTable.removeRow(linhaSelecionadaProdutos);
                produtosTable.setModel(modelProdutoTable);
                jScrollPane1.setViewportView(produtosTable);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Houve um problema em Remover os dados!");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_removerBtnActionPerformed

    private void fecharBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBtnActionPerformed
                                              
       this.dispose();
    }//GEN-LAST:event_fecharBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fecharBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable produtosTable;
    private javax.swing.JButton removerBtn;
    // End of variables declaration//GEN-END:variables
}
