/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package padariafinal.GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import padariafinal.DB.ClienteDB;
import padariafinal.DB.ProdutoDB;
import padariafinal.DB.VendaDB;
import padariafinal.MODEL.Cliente;
import padariafinal.MODEL.Produto;
import padariafinal.MODEL.Venda;

/**
 *
 * @author pa-to
 */
public class RemoverVendaJInternalFrame extends javax.swing.JInternalFrame {

    DefaultTableModel modelVendaTable = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {

            return false;
        }
    };

    public RemoverVendaJInternalFrame() {
        initComponents();
        loadTableVendas();
    }
    private void loadTableVendas() {
        modelVendaTable.addColumn("idCliente"); //0
        modelVendaTable.addColumn("Nome Cliente"); //1
        modelVendaTable.addColumn("idProduto"); //2
        modelVendaTable.addColumn("Nome Produto"); //3
        modelVendaTable.addColumn("Quantidade"); //4
        modelVendaTable.addColumn("Data");//5
         modelVendaTable.addColumn("Valor"); //6
         
         VendaDB  vendaDB= new VendaDB();
         ArrayList<Venda> vendas = vendaDB.getVendas();
         for(int i=0; i<vendas.size();i++){
             Venda venda= (Venda) vendas.get(i);
             int idCliente = venda.getIdCliente();
             int idProduto = venda.getIdProduto();
             String data= venda.getData();
             int quantidade=venda.getQuantidade();
             
             ProdutoDB produtoDB = new ProdutoDB();
             Produto produto = produtoDB.getProduto(idProduto);
             
             ClienteDB clienteDB = new ClienteDB();
             Cliente cliente = clienteDB.getCliente(idCliente);
             
             modelVendaTable.addRow(new Object[]{
             idCliente, cliente.getNome(), idProduto, produto.getNome(), quantidade, data, String.valueOf(produto.getPreco()*quantidade)
             
             });

         }
            vendasTable.setModel(modelVendaTable);
            jScrollPane1.setViewportView(vendasTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vendasTable = new javax.swing.JTable();
        fecharBtn = new javax.swing.JButton();
        removerBtn = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Remover Venda");

        vendasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(vendasTable);

        fecharBtn.setText("Fechar");
        fecharBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharBtnActionPerformed(evt);
            }
        });

        removerBtn.setText("Remover");
        removerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(removerBtn)
                        .addGap(18, 18, 18)
                        .addComponent(fecharBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecharBtn)
                    .addComponent(removerBtn))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBtnActionPerformed
        this.dispose();
      
    }//GEN-LAST:event_fecharBtnActionPerformed
     
    private void removerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBtnActionPerformed
        int linhaSelecionadaVendas = vendasTable.getSelectedRow();

        if (linhaSelecionadaVendas == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma venda da tabela!");
            return;
        }
        int idCliente = (int) vendasTable.getValueAt(linhaSelecionadaVendas, 0);
        int idProduto = (int) vendasTable.getValueAt(linhaSelecionadaVendas, 2);
        VendaDB vendaDB= new VendaDB();
        
        if (vendaDB.delete(idCliente, idProduto)) {
            JOptionPane.showMessageDialog(rootPane, "Venda Removida com sucesso!");
            modelVendaTable.removeRow(linhaSelecionadaVendas);
            vendasTable.setModel(modelVendaTable);
            jScrollPane1.setViewportView(vendasTable);
        }else {
                JOptionPane.showMessageDialog(rootPane, "Houve um problema em Remover a venda!");
            }


    }//GEN-LAST:event_removerBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fecharBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removerBtn;
    private javax.swing.JTable vendasTable;
    // End of variables declaration//GEN-END:variables
}
